input_path = "input" # "input" # TODO This could be an argument.
wip_path = "output"  # "output" # TODO This could be an argument.
log_path = "logs"

overwrite_previous_output = true # TODO This currently won't work if set to false as it will run into errors as the folder already exists.

# Tags that shall be kept (and be beautified).
# Documentation on tag ids (called frames by mutagen): https://mutagen.readthedocs.io/en/latest/api/id3_frames.html#id3v2-3-4-frames
selected_id3_fields = [
    "APIC:",
    "POPM:no@email",
    "TALB",
    "TDRC",
    "TIT2",
    "TPE1",
    "TPE2",
    "TPOS",
    "TRCK",
] # TODO accepted fits better than selected.


# Files and filetypes that shall be deleted.
unwanted_files = [
    ".exe",
    ".nfo",
    ".txt",
    ".url",
    "thumbs.db",
    ".db",
    ".DS_Store",
    ".m3u",
    ".m3u8",
    ".sfv",
    ".pls",
    ".pdf",
    ".zip",
    ".rar",
    ".7z",
    "AlbumArtSmall.jpg",
    ".htm",
    ".html",
    ".ini",
] # Only provide the end of the file(type) here.

# Keywords that exist as track/filename suffixes. The order of the list will be the order in which these suffixes are sorted.
suffix_keywords = [
    "remix",
    "acoustic",
    "instrumental",
    "skit",
    "produced",
    "cut",
    "cutted",
    "short",
    "shorter",
    "bonus",
    "part",
    "pt",
    "feat",
    "live",
]
