"input_path" = "input" # TODO This could be an argument.
"wip_path" = "output" # TODO This could be an argument.



# Tags that shall be kept / improved.
selected_id3_fields = ["POPM:no@email", "TALB", "TDRC", "TIT2", "TPE1", "TPE2", "TPOS", "TRCK"]
# Documentation on tag ids (called frames by mutagen): https://mutagen.readthedocs.io/en/latest/api/id3_frames.html#id3v2-3-4-frames
