input_path = "E:/Audio/!Neu/!2MP3 Cleaner Input"   # "D:/Audio/!Neu/!2MP3 Cleaner Input"   # Default: "input"
output_path = "E:/Audio/!Neu/!3MP3 Cleaner Output" # Default: "output"

threads = 16 # Default: 1

do_clean_output_folder = true # Default: true

# Files and filetypes from the input folder that shall be omitted for the output folder.
# Only provide the end of the file(type) here.
unwanted_files = [
    "*.7z",
    "*.db",
    "*.DS_Store",
    "*.exe",
    "*.htm",
    "*.html",
    "*.ini",
    "*.m3u",
    "*.m3u8",
    "*.nfo",
    "*.pdf",
    "*.pls",
    "*.rar",
    "*.sfv",
    "*.txt",
    "*.url",
    "*.zip",
    "AlbumArtSmall.jpg",
    "thumbs.db",
]
