input_path = "data"    # "input" # TODO This could be an argument.
output_path = "output" # "output" # TODO This could be an argument.

clean_output_folder = true # TODO This currently won't work if set to false as it will run into errors as the folder already exists.

# Files and filetypes that shall be deleted.
unwanted_files = [
    "*.7z",
    "*.db",
    "*.DS_Store",
    "*.exe",
    "*.htm",
    "*.html",
    "*.ini",
    "*.m3u",
    "*.m3u8",
    "*.nfo",
    "*.pdf",
    "*.pls",
    "*.rar",
    "*.sfv",
    "*.txt",
    "*.url",
    "*.zip",
    "AlbumArtSmall.jpg",
    "thumbs.db",
] # Only provide the end of the file(type) here.

# Keywords that exist as track/filename suffixes. The order of the list will be the order in which these suffixes are sorted.
# TODO Are those still needed?
suffix_keywords = [
    "remix",
    "acoustic",
    "instrumental",
    "skit",
    "produced",
    "cut",
    "cutted",
    "short",
    "shorter",
    "bonus",
    "part",
    "pt",
    "feat",
    "live",
]
